services:
  app:
    container_name: smartbudget-app-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    command: sh -c "node --require ts-node/register ./node_modules/typeorm/cli.js migration:run -d ./dist/src/data-source.js && npm run start:prod"
    env_file:
      - .env
    networks:
      - webnet
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
 
  postgres:
    container_name: smartbudget-postgres-db
    image: postgres:16-alpine
    networks:
      - webnet
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  webnet:
volumes:
  pgdata: